server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://127.0.0.1:8001  # lb://member-service目前还不行 因为没有nacos注册中心
          predicates:
            - Path=/member/**